[package]
name = "app-shell"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "app-shell"
path = "src/main.rs"

[dependencies]
winit = { workspace = true }
softbuffer = { workspace = true }
tiny-skia = { workspace = true }
css-types = { workspace = true }
dsl-parser = { workspace = true }
element-core = { workspace = true }
style-system = { workspace = true }
layout-engine = { workspace = true }
render-backend = { workspace = true }
live-runtime = { workspace = true }
